[pytest]
addopts = --import-mode=importlib
testpaths =
    drone/ros2_ws/src/bennu_camera/test
    drone/ros2_ws/src/bennu_core/test
    drone/ros2_ws/src/bennu_dataset/test
    drone/ros2_ws/src/bennu_mission/test
    tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
